name: Deploy Website
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: builds
        run: echo Building
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: "https://www.lucasmuniz.com.br"
    needs: build
    steps:
      - name: Repo Checkout
        uses: actions/checkout@v1
      - name: Hostinger
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{secrets.SERVER_SSH_KEY}}
          ARGS: "-rlgoDvc --delete"
          SOURCE: ""
          REMOTE_HOST: ${{secrets.REMOTE_HOST}}
          REMOTE_USER: ${{secrets.REMOTE_USER}}
          REMOTE_PORT: ${{secrets.REMOTE_PORT}}
          TARGET: ${{vars.TARGET}}